### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by jhaemin** [CAU-OSS-2019/team-project-team10#54]
I cannot connect to 165.194.35.214:26656 protocol and the README does not contain any instruction how to test your application.

![Screen Shot 2019-05-28 at 12 21 54 PM](https://user-images.githubusercontent.com/19797697/58448507-2f6d6080-8143-11e9-853b-4d9b3a0fdc87.png)

**Comment by FelixSeol** [comment]
Server closed. Cause server manager has been at ‘동원 예비군 훈련’. 

...
...

Server will opened at 20:00
