### ISSUE TITLE
검색결과의 의미파악 어려움

### ISSUE THREAD

**Issue by heozeop** [CAU-OSS-2019/team-project-team10#70]
![캡처](https://user-images.githubusercontent.com/29042329/59004052-5880a600-8853-11e9-9df2-e2ab4943a195.PNG)

색깔별 포인트가 todo리스트를 나타낸 다는 것을 각 지점을 클릭하여 인지 했으나, 처음 사용하는 사용자들에게는 어색할 것 같습니다. 따라서 각 포인트의 색깔들과 todo list를 맵핑하면 좋을 것 같습니다. 감사합니다.

**Comment by lee-garden** [comment]
이슈 사항에 대해 인지하였고 해당부분 구현 완료되어 곧 머지 할 예정입니다 감사합니다.
