### ISSUE TITLE
해당 포트로 접속이 되지 않습니다. 

### ISSUE THREAD

**Issue by hoonv** [CAU-OSS-2019/team-project-team10#88]
![image](https://user-images.githubusercontent.com/46335714/59326159-92a0ea80-8d20-11e9-9633-b2099b03c1fe.png)

서버가 닫혀있는건지 아니면 제 클라이언트문제인지 궁금합니다.

**Comment by FelixSeol** [comment]
api 서버만 제공되고 있었습니다.

client 페이지도 서비스되고있습니다.
