### ISSUE TITLE
Assemble이 제대로 작동하지 않습니다.

### ISSUE THREAD

**Issue by Reichidad** [CAU-OSS-2019/team-project-team10#96]
![image](https://user-images.githubusercontent.com/47580804/59907480-1dcb6000-9446-11e9-9ff7-8e645a14aa2d.png)

Assemble 버튼을 눌러도 주변의 노래방에 대한 표시가 나타나지않습니다.

**Comment by CJBJ1** [comment]
현재 서버를 열어놓지 않았습니다
